## static_countries
UPDATE static_countries SET cn_short_cz='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_cz='Spojené arabské emiráty' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_cz='Afghánistán' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_cz='Antigua a Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_cz='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_cz='Albánie' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_cz='Arménie' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_cz='Nizozemské Antily' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_cz='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_cz='Antarktida' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_cz='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_cz='Americká Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_cz='Rakousko' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_cz='Austrálie' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_cz='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_cz='Ázerbájdžán' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_cz='Bosna a Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_cz='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_cz='Bangladéš' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_cz='Belgie' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_cz='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_cz='Bulharsko' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_cz='Bahrajn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_cz='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_cz='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_cz='Bermudy' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_cz='Sultanát Brunej' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_cz='Bolívie' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_cz='Brazílie' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_cz='Bahamy' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_cz='Bhútán' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_cz='Bouvetův ostrov' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_cz='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_cz='Bělorusko' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_cz='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_cz='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_cz='Kokosové (Keelingovy) ostrovy' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_cz='Demokratická republika Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_cz='Středoafrická republika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_cz='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_cz='Švýcarsko' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_cz='Pobřeží slonoviny' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_cz='Cookovy ostrovy' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_cz='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_cz='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_cz='Čína' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_cz='Kolumbie' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_cz='Kostarika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_cz='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_cz='Kapverdské ostrovy' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_cz='Vánoční ostrov' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_cz='Kypr' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_cz='Česká republika' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_cz='Německo' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_cz='Džibutsko' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_cz='Dánsko' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_cz='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_cz='Dominikánská republika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_cz='Alžírsko' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_cz='Ekvádor' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_cz='Estonsko' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_cz='Egypt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_cz='Západní Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_cz='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_cz='Španělsko' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_cz='Etiopie' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_cz='Finsko' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_cz='Fidži' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_cz='Falklandy' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_cz='Mikronésie' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_cz='Faerské ostrovy' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_cz='Francie' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_cz='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_cz='Velká Británie' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_cz='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_cz='Gruzie' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_cz='Francouzská Guayana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_cz='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_cz='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_cz='Grónsko' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_cz='Gambie' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_cz='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_cz='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_cz='Rovníková Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_cz='Řecko' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_cz='Jižní Georgie a Jižní Sandwichovy ostrovy' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_cz='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_cz='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_cz='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_cz='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_cz='Zvláštní správní oblast Čínské lidové republiky Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_cz='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_cz='Chorvatsko' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_cz='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_cz='Maďarsko' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_cz='Indonésie' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_cz='Irsko' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_cz='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_cz='Indie' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_cz='Britské indickooceánské území' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_cz='Irák' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_cz='Írán' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_cz='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_cz='Itálie' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_cz='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_cz='Jordánsko' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_cz='Japonsko' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_cz='Keňa' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_cz='Kyrgyzstán' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_cz='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_cz='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_cz='Komory' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_cz='Svatý Kryštof a Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_cz='Korejská lidově demokratická republika' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_cz='Korejská republika' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_cz='Kuvajt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_cz='Kajmanské ostrovy' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_cz='Kazachstán' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_cz='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_cz='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_cz='Svatá Lucie' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_cz='Lichtenštejnsko' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_cz='Srí Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_cz='Libérie' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_cz='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_cz='Litva' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_cz='Lucembursko' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_cz='Lotyšsko' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_cz='Libye' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_cz='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_cz='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_cz='Moldavská republika' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_cz='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_cz='Marshallovy ostrovy' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_cz='Makedonie' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_cz='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_cz='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_cz='Mongolsko' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_cz='Zvláštní správní oblast Čínské lidové republiky Macao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_cz='Severní Mariany' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_cz='Martinik' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_cz='Mauritánie' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_cz='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_cz='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_cz='Mauricius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_cz='Maledivy' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_cz='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_cz='Mexiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_cz='Malajsie' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_cz='Mosambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_cz='Namibie' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_cz='Nová Kaledonie' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_cz='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_cz='Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_cz='Nigérie' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_cz='Nikaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_cz='Nizozemsko' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_cz='Norsko' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_cz='Nepál' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_cz='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_cz='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_cz='Nový Zéland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_cz='Omán' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_cz='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_cz='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_cz='Francouzská Polynésie' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_cz='Papua-Nová Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_cz='Filipíny' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_cz='Pákistán' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_cz='Polsko' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_cz='Saint Pierre a Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_cz='Pitcairnovy ostrovy' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_cz='Portoriko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_cz='Portugalsko' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_cz='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_cz='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_cz='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_cz='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_cz='Rumunsko' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_cz='Ruská federace' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_cz='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_cz='Saúdská Arábie' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_cz='Šalamounovy ostrovy' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_cz='Seychely' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_cz='Súdán' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_cz='Švédsko' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_cz='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_cz='Svatá Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_cz='Slovinsko' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_cz='Špicberky a Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_cz='Slovensko' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_cz='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_cz='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_cz='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_cz='Somálsko' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_cz='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_cz='Svatý Tomáš a Princův ostrov' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_cz='Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_cz='Sýrie' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_cz='Svazijsko' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_cz='Turks a Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_cz='Čad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_cz='Francouzská jižní a antarktická území' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_cz='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_cz='Thajsko' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_cz='Tádžikistán' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_cz='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_cz='Turkmenistán' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_cz='Tunisko' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_cz='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_cz='Východní Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_cz='Turecko' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_cz='Trinidad a Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_cz='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_cz='Tchaj-wan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_cz='Tanzanie' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_cz='Ukrajina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_cz='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_cz='Americká Oceánie' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_cz='Spojené státy americké' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_cz='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_cz='Uzbekistán' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_cz='Vatikán' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_cz='Svatý Vincenc a Grenadiny' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_cz='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_cz='Britské Panenské ostrovy' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_cz='Americké Panenské ostrovy' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_cz='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_cz='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_cz='Wallis a Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_cz='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_cz='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_cz='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_cz='Jihoafrická republika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_cz='Zambie' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_cz='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_cz='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_cz='Srbsko a Černá Hora' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_cz='Ålandy' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_cz='Heardův ostrov a McDonaldovy ostrovy' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_cz='Černá Hora' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_cz='Srbsko' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_cz='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_cz='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_cz='Ostrov Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_cz='Svatý Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_cz='Svatý Bartoloměj' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_cz='Bonaire, Svatý Eustach a Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_cz='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_cz='Svatý Martin' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_cz='Jižní Súdán' WHERE cn_iso_2='SS';

## Old query does not work with new update script
## UPDATE static_countries SET cn_official_name_cz = cn_short_cz WHERE cn_official_name_cz='' OR cn_official_name_cz IS NULL;

UPDATE static_countries SET cn_official_name_cz='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_official_name_cz='Spojené arabské emiráty' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_official_name_cz='Afghánistán' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_official_name_cz='Antigua a Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_official_name_cz='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_official_name_cz='Albánie' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_official_name_cz='Arménie' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_official_name_cz='Nizozemské Antily' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_official_name_cz='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_official_name_cz='Antarktida' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_official_name_cz='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_official_name_cz='Americká Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_official_name_cz='Rakousko' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_official_name_cz='Austrálie' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_official_name_cz='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_official_name_cz='Ázerbájdžán' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_official_name_cz='Bosna a Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_official_name_cz='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_official_name_cz='Bangladéš' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_official_name_cz='Belgie' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_official_name_cz='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_official_name_cz='Bulharsko' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_official_name_cz='Bahrajn' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_official_name_cz='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_official_name_cz='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_official_name_cz='Bermudy' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_official_name_cz='Sultanát Brunej' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_official_name_cz='Bolívie' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_official_name_cz='Brazílie' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_official_name_cz='Bahamy' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_official_name_cz='Bhútán' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_official_name_cz='Bouvetův ostrov' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_official_name_cz='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_official_name_cz='Bělorusko' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_official_name_cz='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_official_name_cz='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_official_name_cz='Kokosové (Keelingovy) ostrovy' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_official_name_cz='Demokratická republika Kongo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_official_name_cz='Středoafrická republika' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_official_name_cz='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_official_name_cz='Švýcarsko' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_official_name_cz='Pobřeží slonoviny' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_official_name_cz='Cookovy ostrovy' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_official_name_cz='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_official_name_cz='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_official_name_cz='Čína' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_official_name_cz='Kolumbie' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_official_name_cz='Kostarika' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_official_name_cz='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_official_name_cz='Kapverdské ostrovy' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_official_name_cz='Vánoční ostrov' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_official_name_cz='Kypr' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_official_name_cz='Česká republika' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_official_name_cz='Německo' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_official_name_cz='Džibutsko' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_official_name_cz='Dánsko' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_official_name_cz='Dominika' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_official_name_cz='Dominikánská republika' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_official_name_cz='Alžírsko' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_official_name_cz='Ekvádor' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_official_name_cz='Estonsko' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_official_name_cz='Egypt' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_official_name_cz='Západní Sahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_official_name_cz='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_official_name_cz='Španělsko' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_official_name_cz='Etiopie' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_official_name_cz='Finsko' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_official_name_cz='Fidži' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_official_name_cz='Falklandy' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_official_name_cz='Mikronésie' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_official_name_cz='Faerské ostrovy' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_official_name_cz='Francie' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_official_name_cz='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_official_name_cz='Velká Británie' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_official_name_cz='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_official_name_cz='Gruzie' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_official_name_cz='Francouzská Guayana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_official_name_cz='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_official_name_cz='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_official_name_cz='Grónsko' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_official_name_cz='Gambie' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_official_name_cz='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_official_name_cz='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_official_name_cz='Rovníková Guinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_official_name_cz='Řecko' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_official_name_cz='Jižní Georgie a Jižní Sandwichovy ostrovy' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_official_name_cz='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_official_name_cz='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_official_name_cz='Guinea-Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_official_name_cz='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_official_name_cz='Zvláštní správní oblast Čínské lidové republiky Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_official_name_cz='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_official_name_cz='Chorvatsko' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_official_name_cz='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_official_name_cz='Maďarsko' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_official_name_cz='Indonésie' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_official_name_cz='Irsko' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_official_name_cz='Izrael' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_official_name_cz='Indie' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_official_name_cz='Britské indickooceánské území' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_official_name_cz='Irák' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_official_name_cz='Írán' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_official_name_cz='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_official_name_cz='Itálie' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_official_name_cz='Jamajka' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_official_name_cz='Jordánsko' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_official_name_cz='Japonsko' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_official_name_cz='Keňa' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_official_name_cz='Kyrgyzstán' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_official_name_cz='Kambodža' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_official_name_cz='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_official_name_cz='Komory' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_official_name_cz='Svatý Kryštof a Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_official_name_cz='Korejská lidově demokratická republika' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_official_name_cz='Korejská republika' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_official_name_cz='Kuvajt' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_official_name_cz='Kajmanské ostrovy' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_official_name_cz='Kazachstán' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_official_name_cz='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_official_name_cz='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_official_name_cz='Svatá Lucie' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_official_name_cz='Lichtenštejnsko' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_official_name_cz='Srí Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_official_name_cz='Libérie' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_official_name_cz='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_official_name_cz='Litva' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_official_name_cz='Lucembursko' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_official_name_cz='Lotyšsko' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_official_name_cz='Libye' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_official_name_cz='Maroko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_official_name_cz='Monako' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_official_name_cz='Moldavská republika' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_official_name_cz='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_official_name_cz='Marshallovy ostrovy' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_official_name_cz='Makedonie' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_official_name_cz='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_official_name_cz='Myanmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_official_name_cz='Mongolsko' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_official_name_cz='Zvláštní správní oblast Čínské lidové republiky Macao' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_official_name_cz='Severní Mariany' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_official_name_cz='Martinik' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_official_name_cz='Mauritánie' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_official_name_cz='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_official_name_cz='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_official_name_cz='Mauricius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_official_name_cz='Maledivy' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_official_name_cz='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_official_name_cz='Mexiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_official_name_cz='Malajsie' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_official_name_cz='Mosambik' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_official_name_cz='Namibie' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_official_name_cz='Nová Kaledonie' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_official_name_cz='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_official_name_cz='Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_official_name_cz='Nigérie' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_official_name_cz='Nikaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_official_name_cz='Nizozemsko' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_official_name_cz='Norsko' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_official_name_cz='Nepál' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_official_name_cz='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_official_name_cz='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_official_name_cz='Nový Zéland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_official_name_cz='Omán' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_official_name_cz='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_official_name_cz='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_official_name_cz='Francouzská Polynésie' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_official_name_cz='Papua-Nová Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_official_name_cz='Filipíny' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_official_name_cz='Pákistán' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_official_name_cz='Polsko' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_official_name_cz='Saint Pierre a Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_official_name_cz='Pitcairnovy ostrovy' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_official_name_cz='Portoriko' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_official_name_cz='Portugalsko' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_official_name_cz='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_official_name_cz='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_official_name_cz='Katar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_official_name_cz='Réunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_official_name_cz='Rumunsko' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_official_name_cz='Ruská federace' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_official_name_cz='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_official_name_cz='Saúdská Arábie' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_official_name_cz='Šalamounovy ostrovy' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_official_name_cz='Seychely' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_official_name_cz='Súdán' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_official_name_cz='Švédsko' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_official_name_cz='Singapur' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_official_name_cz='Svatá Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_official_name_cz='Slovinsko' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_official_name_cz='Špicberky a Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_official_name_cz='Slovensko' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_official_name_cz='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_official_name_cz='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_official_name_cz='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_official_name_cz='Somálsko' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_official_name_cz='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_official_name_cz='Svatý Tomáš a Princův ostrov' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_official_name_cz='Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_official_name_cz='Sýrie' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_official_name_cz='Svazijsko' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_official_name_cz='Turks a Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_official_name_cz='Čad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_official_name_cz='Francouzská jižní a antarktická území' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_official_name_cz='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_official_name_cz='Thajsko' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_official_name_cz='Tádžikistán' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_official_name_cz='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_official_name_cz='Turkmenistán' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_official_name_cz='Tunisko' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_official_name_cz='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_official_name_cz='Východní Timor' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_official_name_cz='Turecko' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_official_name_cz='Trinidad a Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_official_name_cz='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_official_name_cz='Tchaj-wan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_official_name_cz='Tanzanie' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_official_name_cz='Ukrajina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_official_name_cz='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_official_name_cz='Americká Oceánie' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_official_name_cz='Spojené státy americké' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_official_name_cz='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_official_name_cz='Uzbekistán' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_official_name_cz='Vatikán' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_official_name_cz='Svatý Vincenc a Grenadiny' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_official_name_cz='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_official_name_cz='Britské Panenské ostrovy' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_official_name_cz='Americké Panenské ostrovy' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_official_name_cz='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_official_name_cz='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_official_name_cz='Wallis a Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_official_name_cz='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_official_name_cz='Jemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_official_name_cz='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_official_name_cz='Jihoafrická republika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_official_name_cz='Zambie' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_official_name_cz='Zimbabwe' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_official_name_cz='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_official_name_cz='Srbsko a Černá Hora' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_official_name_cz='Ålandy' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_official_name_cz='Heardův ostrov a McDonaldovy ostrovy' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_official_name_cz='Černá Hora' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_official_name_cz='Srbsko' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_official_name_cz='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_official_name_cz='Guernsey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_official_name_cz='Ostrov Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_official_name_cz='Svatý Martin' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_official_name_cz='Svatý Bartoloměj' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_official_name_cz='Bonaire, Svatý Eustach a Saba' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_official_name_cz='Curaçao' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_official_name_cz='Svatý Martin' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_official_name_cz='Jižní Súdán' WHERE cn_iso_2='SS';
